Suppress warning about exceeding the soft limit for number of files
markt-de/puppet-solr pull request #7
Opened 2022-10-03 09:38 UTC by siebrand

Observed in the puppet client log without this change:

  The directory '/opt/staging' contains 2091 entries, which exceeds the
  default soft limit 1000 and may cause excessive resource consumption and
  degraded performance. To remove this warning set a value for `max_files`
  parameter or consider using an alternate method to manage large directory
  trees

This fixes #5.

2022-10-26 21:56 UTC, fraenki requested changes

2022-10-26 21:56 UTC, fraenki commented on manifests/install.pp
> +    max_files => 3000,
I'd rather set this to `-1` and use a more comprehensive comment. Could you update your PR please? :)

2022-10-27 08:10 UTC, siebrand commented
I've updated the PR based on the feedback by @fraenki

2022-10-30 09:06 UTC, merged

2022-10-30 09:06 UTC, fraenki commented
Merged, thanks!